name: t_store
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

# --------------------- PACKAGES --------------------#
dependencies:
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.5
  get: ^4.6.6
  get_storage: ^2.1.1
  http: ^1.1.0
  iconsax: ^0.0.8
  intl: ^0.18.1
  logger: ^2.0.2+1
  lottie: ^2.7.0
  phlox_animations: ^2.1.1
  smooth_page_indicator: ^1.1.0
  url_launcher: ^6.2.1

# --------------------- PACKAGES END --------------------#
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  # --------------------- LOCAL ASSETS --------------------#
  assets:
    - assets/logos/
    - assets/icons/brands/
    - assets/images/banners/
    - assets/images/products/
    - assets/images/on_boarding_images/
    - assets/images/animations/
    - assets/icons/categories/
  # --------------------- LOCAL FONTS --------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
